-- Colorauta - Supabase setup
-- 1) Cole este SQL no Supabase em SQL Editor > New query > Run.
-- 2) Depois crie seu usuario em Authentication > Users.
-- 3) Pegue o ID do usuario e rode:
-- insert into public.admin_users (user_id) values ('COLE-O-USER-ID-AQUI');

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  emoji text not null default '📦',
  image text default '',
  description text not null default '',
  color text not null default '#c11c84',
  color2 text not null default '#058f9c',
  badge text,
  featured boolean not null default false,
  best_seller boolean not null default false,
  active boolean not null default true,
  delivery_time text not null default 'Sob consulta',
  availability text not null default 'Disponível para orçamento',
  details text[] not null default '{}',
  old_price integer,
  selected_variant text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  label text not null,
  price integer not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products alter column image drop not null;
alter table public.products add column if not exists best_seller boolean not null default false;

create index if not exists products_active_featured_idx on public.products(active, featured, sort_order);
create index if not exists products_category_idx on public.products(category);
create index if not exists product_variants_product_id_idx on public.product_variants(product_id, sort_order);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists product_variants_set_updated_at on public.product_variants;
create trigger product_variants_set_updated_at
before update on public.product_variants
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

drop policy if exists admin_users_select_own on public.admin_users;
create policy admin_users_select_own
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists products_public_read_active on public.products;
create policy products_public_read_active
on public.products for select
to anon, authenticated
using (active = true);

drop policy if exists products_admin_read_all on public.products;
create policy products_admin_read_all
on public.products for select
to authenticated
using (public.is_admin());

drop policy if exists products_admin_insert on public.products;
create policy products_admin_insert
on public.products for insert
to authenticated
with check (public.is_admin());

drop policy if exists products_admin_update on public.products;
create policy products_admin_update
on public.products for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists products_admin_delete on public.products;
create policy products_admin_delete
on public.products for delete
to authenticated
using (public.is_admin());

drop policy if exists variants_public_read_active_products on public.product_variants;
create policy variants_public_read_active_products
on public.product_variants for select
to anon, authenticated
using (
  exists (
    select 1 from public.products
    where products.id = product_variants.product_id
    and products.active = true
  )
);

drop policy if exists variants_admin_read_all on public.product_variants;
create policy variants_admin_read_all
on public.product_variants for select
to authenticated
using (public.is_admin());

drop policy if exists variants_admin_insert on public.product_variants;
create policy variants_admin_insert
on public.product_variants for insert
to authenticated
with check (public.is_admin());

drop policy if exists variants_admin_update on public.product_variants;
create policy variants_admin_update
on public.product_variants for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists variants_admin_delete on public.product_variants;
create policy variants_admin_delete
on public.product_variants for delete
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists product_images_admin_insert on storage.objects;
create policy product_images_admin_insert
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists product_images_admin_update on storage.objects;
create policy product_images_admin_update
on storage.objects for update
to authenticated
using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists product_images_admin_delete on storage.objects;
create policy product_images_admin_delete
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images' and public.is_admin());

truncate table public.product_variants restart identity cascade;
truncate table public.products restart identity cascade;

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (1, 'Cartão de Visita', 'Papelaria', '🪪', 'images/cartao.png', 'Cartões em couchê 300g com opções de quantidade e impressão', '#7B2FFF', '#FF2D78', '🔥 Mais Vendido', true, true, '3 a 5 dias úteis', 'Disponível para orçamento', array['Papel couchê 300g', 'Quantidades de 100 a 2000 unidades', 'Opções só frente ou frente e verso', 'Acabamento profissional', 'Ideal para apresentação comercial']::text[], null, '1000 un. Só frente', 0);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '100 un. Só frente', 2490, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '100 un. Frente e Verso', 3490, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '250 un. Só frente', 3990, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '250 un. Frente e Verso', 4990, 3);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '500 un. Só frente', 5490, 4);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '500 un. Frente e Verso', 6490, 5);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '1000 un. Só frente', 6490, 6);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '1000 un. Frente e Verso', 7990, 7);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '2000 un. Só frente', 11990, 8);
insert into public.product_variants (product_id, label, price, sort_order) values (1, '2000 un. Frente e Verso', 14990, 9);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (2, 'Banner Lona 1x2m', 'Banners', '🏷️', 'images/banner.jpg', 'Impressão digital, acabamento com ilhoses', '#FF6B00', '#FFD600', null, true, true, '2 a 4 dias úteis', 'Disponível para orçamento', array['Lona resistente para uso interno ou externo', 'Acabamento com ilhoses ou bainhas', 'Impressão digital em alta definição']::text[], null, 'Com Ilhoses', 1);
insert into public.product_variants (product_id, label, price, sort_order) values (2, 'Com Ilhoses', 7990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (2, 'Com Bainhas', 8490, 1);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (3, 'Adesivo Vinil', 'Adesivos', '🏷️', 'images/adesivo.jpg', 'Corte especial, impressão UV', '#00B4FF', '#7B2FFF', '🆕 Novo', true, true, '3 a 6 dias úteis', 'Disponível para orçamento', array['Vinil adesivo personalizado', 'Opções em A4, A3 e A2', 'Indicado para etiquetas, decoração e comunicação visual']::text[], null, 'A4', 2);
insert into public.product_variants (product_id, label, price, sort_order) values (3, 'A4', 2500, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (3, 'A3', 4200, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (3, 'A2', 7500, 2);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (4, 'Flyer 14x20', 'Impressão', '📄', 'images/panfleto.png', 'Couchê 90g, impressão colorida', '#FF2D78', '#FF6B00', '💥 Oferta', true, true, '3 a 5 dias úteis', 'Disponível para orçamento', array['Formato 14x20 cm', 'Papel couchê 90g', 'Opções de impressão só frente ou frente e verso']::text[], null, '1000 un. Só frente', 3);
insert into public.product_variants (product_id, label, price, sort_order) values (4, '1000 un. Só frente', 3990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (4, '1000 un. Frente e Verso', 4990, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (4, '2500 un. Só frente', 2980, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (4, '2500 un. Frente e Verso', 7490, 3);
insert into public.product_variants (product_id, label, price, sort_order) values (4, '5000 un. Só frente', 9990, 4);
insert into public.product_variants (product_id, label, price, sort_order) values (4, '5000 un. Frente e Verso', 12490, 5);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (5, 'Caneca Cerâmica', 'Festas', '☕', null, 'Sublimação full, capacidade 325ml', '#00F0FF', '#00B4FF', null, false, true, '5 a 7 dias úteis', 'Sob consulta', array['Sublimação full color', 'Capacidade 325ml']::text[], null, 'Branca', 4);
insert into public.product_variants (product_id, label, price, sort_order) values (5, 'Branca', 3500, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (5, 'Mágica', 4500, 1);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (6, 'Camiseta Estampada', 'Festas', '👕', null, '100% algodão, estampa DTF full color', '#7B2FFF', '#FF2D78', null, false, true, '5 a 8 dias úteis', 'Sob consulta', array['Estampa DTF full color', 'Tamanhos P ao GG']::text[], null, 'M', 5);
insert into public.product_variants (product_id, label, price, sort_order) values (6, 'P', 6500, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (6, 'M', 6500, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (6, 'G', 6500, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (6, 'GG', 7500, 3);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (7, 'Folder A4 Dobrado', 'Papelaria', '📰', null, 'Couchê 150g, dobra dupla ou tripla', '#FFD600', '#FF6B00', null, false, true, '4 a 7 dias úteis', 'Disponível para orçamento', array['Couchê 150g', 'Dobra dupla ou tripla']::text[], null, 'Dupla Só frente', 6);
insert into public.product_variants (product_id, label, price, sort_order) values (7, 'Dupla Só frente', 2990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (7, 'Dupla Frente e Verso', 3990, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (7, 'Tripla Só frente', 3490, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (7, 'Tripla Frente e Verso', 4490, 3);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (8, 'Lona Impressa 2x3m', 'Banners', '🖼️', 'images/banner.jpg', 'Alta definição, resistente ao sol', '#FF6B00', '#FF2D78', '⭐ Premium', true, true, '3 a 5 dias úteis', 'Disponível para orçamento', array['Lona em alta definição', 'Boa resistência ao sol', 'Indicada para fachadas, eventos e promoções']::text[], null, 'Com Ilhoses', 7);
insert into public.product_variants (product_id, label, price, sort_order) values (8, 'Com Ilhoses', 14990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (8, 'Sem Acabamento', 13490, 1);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (9, 'Etiqueta Adesiva', 'Adesivos', '🔖', null, 'Rolo c/ 1000 un., impressão colorida', '#00B4FF', '#00F0FF', null, false, true, '4 a 7 dias úteis', 'Disponível para orçamento', array['Rolo com 1000 unidades', 'Formatos redondo, retangular ou personalizado']::text[], null, 'Redonda', 8);
insert into public.product_variants (product_id, label, price, sort_order) values (9, 'Redonda', 5990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (9, 'Retangular', 5990, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (9, 'Personalizada', 7990, 2);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (10, 'Envelope Personalizado', 'Papelaria', '✉️', null, 'Papel offset 90g, impressão colorida', '#7B2FFF', '#00B4FF', null, false, true, '4 a 7 dias úteis', 'Disponível para orçamento', array['Papel offset 90g', 'Modelos carta e ofício']::text[], null, 'Carta Só frente', 9);
insert into public.product_variants (product_id, label, price, sort_order) values (10, 'Carta Só frente', 1990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (10, 'Carta Frente e Verso', 2490, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (10, 'Ofício Só frente', 2290, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (10, 'Ofício Frente e Verso', 2790, 3);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (11, 'Squeeze Plástico', 'Festas', '🧴', null, '600ml, impressão silk ou digital', '#FF2D78', '#7B2FFF', null, false, true, '5 a 8 dias úteis', 'Sob consulta', array['600ml', 'Impressão silk ou digital']::text[], null, 'Silk', 10);
insert into public.product_variants (product_id, label, price, sort_order) values (11, 'Silk', 2800, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (11, 'Digital', 3200, 1);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (12, 'Calendário de Mesa', 'Papelaria', '📅', null, '12 folhas + capa, laminação fosca', '#FFD600', '#00F0FF', '🎄 Natal', true, true, '5 a 7 dias úteis', 'Disponível por temporada', array['12 folhas + capa', 'Laminação fosca', 'Boa opção para brindes corporativos']::text[], null, 'Horizontal', 11);
insert into public.product_variants (product_id, label, price, sort_order) values (12, 'Horizontal', 4500, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (12, 'Vertical', 4500, 1);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (13, 'Papel Timbrado', 'Corporativas', '📄', null, 'Papel timbrado para propostas, contratos e comunicação empresarial', '#7B2FFF', '#00B4FF', '🏢 Corporativo', true, true, '3 a 5 dias úteis', 'Disponível para orçamento', array['Papel offset 90g', 'Impressão colorida com identidade da empresa', 'Indicado para documentos, propostas e comunicados']::text[], null, '500 un. Só frente', 12);
insert into public.product_variants (product_id, label, price, sort_order) values (13, '100 un. Só frente', 3990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (13, '250 un. Só frente', 6990, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (13, '500 un. Só frente', 10990, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (13, '1000 un. Só frente', 17990, 3);
insert into public.product_variants (product_id, label, price, sort_order) values (13, '2000 un. Só frente', 32990, 4);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (14, 'Convite Personalizado', 'Festas', '🎉', null, 'Convites para aniversários, chás, eventos e comemorações', '#FF2D78', '#FFD600', '🎈 Festas', true, true, '4 a 6 dias úteis', 'Disponível para orçamento', array['Impressão colorida', 'Opções de papel e acabamento', 'Ideal para festas infantis, eventos e celebrações']::text[], null, '100 un. Só frente', 13);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '100 un. Só frente', 4990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '100 un. Frente e Verso', 6490, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '250 un. Só frente', 8990, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '250 un. Frente e Verso', 10990, 3);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '500 un. Só frente', 15990, 4);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '500 un. Frente e Verso', 18990, 5);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '1000 un. Só frente', 28990, 6);
insert into public.product_variants (product_id, label, price, sort_order) values (14, '1000 un. Frente e Verso', 34990, 7);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (15, 'Tag para Presente', 'Presentes', '🎁', null, 'Tags personalizadas para embalagens, lembranças e presentes', '#00B4FF', '#FF2D78', '🎁 Presente', true, true, '3 a 5 dias úteis', 'Disponível para orçamento', array['Couchê com impressão colorida', 'Ótimo para lembrancinhas e embalagens especiais', 'Pode ser usado em datas comemorativas e eventos']::text[], null, '250 un. Só frente', 14);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '100 un. Só frente', 2990, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '100 un. Frente e Verso', 3990, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '250 un. Só frente', 5490, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '250 un. Frente e Verso', 6990, 3);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '500 un. Só frente', 8990, 4);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '500 un. Frente e Verso', 10990, 5);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '1000 un. Só frente', 15990, 6);
insert into public.product_variants (product_id, label, price, sort_order) values (15, '1000 un. Frente e Verso', 19990, 7);

insert into public.products (id, name, category, emoji, image, description, color, color2, badge, featured, active, delivery_time, availability, details, old_price, selected_variant, sort_order) values (16, 'Cartão Fidelidade', 'Corporativas', '💼', null, 'Cartões para programas de fidelidade, atendimento e relacionamento', '#FFD600', '#FF6B00', null, true, true, '3 a 5 dias úteis', 'Disponível para orçamento', array['Formato prático para carteira', 'Ideal para salões, lojas, delivery e prestadores de serviço', 'Pode ser feito só frente ou frente e verso']::text[], null, '500 un. Só frente', 15);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '100 un. Só frente', 2490, 0);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '100 un. Frente e Verso', 3490, 1);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '250 un. Só frente', 3990, 2);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '250 un. Frente e Verso', 4990, 3);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '500 un. Só frente', 5490, 4);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '500 un. Frente e Verso', 6490, 5);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '1000 un. Só frente', 6490, 6);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '1000 un. Frente e Verso', 7990, 7);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '2000 un. Só frente', 11990, 8);
insert into public.product_variants (product_id, label, price, sort_order) values (16, '2000 un. Frente e Verso', 14990, 9);

update public.products
set best_seller = true
where id in (1, 2, 3, 4, 8);

select setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1));
select setval(pg_get_serial_sequence('public.product_variants', 'id'), coalesce((select max(id) from public.product_variants), 1));
